# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 48584bada10810e47df255dabe1d39236b19b9317fece3ca7f6ec372bef7909b7fa4371ccd3a497670721f042a1f79e099d673cc52aa23db901aba0e6e9336fb

test:
  secret_key_base: af3c0dd2ab2654d4d8edb1eaa91799be0ff773cee9e8914b63315a338fe6db7b0b9c2d3190571e929fb3b05fb6d43294e23c14d7186eb09687408ad830f968a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
